language: csharp
solution: sample_proj.sln
deploy:
  provider: releases
  api_key: ff3bd8227ea02af0a236ad97d5006e99eb119ee4
  file: sample_proj.exe
  skip_cleanup: true
  api-key:
    secure: Kh1+94sSkmmBYuUiYTAmVVPH7ztodmZHfnP/WzgLmWqKJmQ/xiXtB1yDei2JjxPurVtmuNH0HPcGUFWMW+7pYZKHdYCWZbVJIgvSCt/weLwi69DR5IY/uVGFoCTqiOJO//CQZ7EUEa1eM1fKPAWgCy3xHclhY/xrEzdfPwT8Lvii2xfYT8L+q4ESeFXSX70TYIVIhtz1VuMXSExtxVIVPzMYkS/9wBFslhBq2TEptzNBVYCHI05Xi+y6NdCLgVN4ojmtg5uYxGXusVMQZRXF0AgwhYUouRBGiuHHt2Dp/ejbyy2f4ZV/j0L+YxyTeAuLAmN0UEtfSaEqp8NGzPRHR6nA4638EswN2oE/9pb00I94NZR97CDa8bMFMrN4k4ScDsa0x/RJCnyISl6U6k+FwV54JohxSmkVmCuxw0ni9bVjRIPk0NvIlu1yE/f674k6vmXtJey6QBlGOd4VsaPHhL+3Sh4BUNYJYs8WTaspD0uRQjcJICaovaJ10NE7cyMmRgcPAWFYnRS4n59zxk6/8L/JqjbkyYdH7AxKsltlkl9G98l41upbHLkZwW63e2Wa7oht0sqWltoQSDYMi5aLzjdJmovDvJhJIIzi3pHMRXcbTFCLTxW+n4I3y39cAYcKKmEVfIk5ZzvJ1WfpV2XFwKa/0r7OsTpACA3ISLZsr0A=
